server:
  port: ${PORT:8002}

spring:
  application:
    name: msvc-cursos
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres14}:${DB_PORT:5432}/${DB_DATABASE:msvc_cursos}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:83Dakota77}

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.puente.springcloud.msvc.cursos.msvc_cursos: DEBUG

msvc:
  usuarios:
    url: ${USUARIOS_URL:http://msvc-usuarios:8001/api/v1/usuarios}




